/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

/// <reference types="truffle-typings" />

import * as TruffleContracts from ".";

declare global {
  namespace Truffle {
    interface Artifacts {
      require(name: "ContractProxy"): TruffleContracts.ContractProxyContract;
      require(name: "EIP20Standard"): TruffleContracts.EIP20StandardContract;
      require(name: "ERC20Token"): TruffleContracts.ERC20TokenContract;
      require(
        name: "GasDelegationBlacklist"
      ): TruffleContracts.GasDelegationBlacklistContract;
      require(
        name: "GasDelegationWhitelist"
      ): TruffleContracts.GasDelegationWhitelistContract;
      require(
        name: "LinearMintableToken"
      ): TruffleContracts.LinearMintableTokenContract;
      require(name: "MainBridge"): TruffleContracts.MainBridgeContract;
      require(name: "MainToken"): TruffleContracts.MainTokenContract;
      require(name: "MainTokenProxy"): TruffleContracts.MainTokenProxyContract;
      require(name: "Migrations"): TruffleContracts.MigrationsContract;
      require(name: "Ownable"): TruffleContracts.OwnableContract;
      require(name: "SideBridge"): TruffleContracts.SideBridgeContract;
      require(name: "SideToken"): TruffleContracts.SideTokenContract;
      require(
        name: "TestingERC20Token"
      ): TruffleContracts.TestingERC20TokenContract;
      require(
        name: "TestingLinearMintableMainToken"
      ): TruffleContracts.TestingLinearMintableMainTokenContract;
      require(
        name: "TestTokenRecipient"
      ): TruffleContracts.TestTokenRecipientContract;
      require(name: "TokenRecipient"): TruffleContracts.TokenRecipientContract;
      require(name: "TokenVesting"): TruffleContracts.TokenVestingContract;
      require(
        name: "WhitelistAdminRole"
      ): TruffleContracts.WhitelistAdminRoleContract;
    }
  }
}
